### ISSUE TITLE
IBC support in the marker module

### ISSUE THREAD

**Issue by jtalis** [provenance-io/provenance#1093]
## Summary

There is a need to create a marker on the destination chain using a source chain transaction

## Problem Definition

We are looking to use a restricted marker in a private zone, and then transfer coins from that marker to the destination chain and have them still be restricted.

Without this feature it may be possible to create the marker ahead of time on the destination chain by determining the ibc denom name and creating a restricted marker with that name. However, ibc denoms don't pass the marker denom validation and would require a gov proposal to create them ahead of time. This would be too cumbersome when wanting to frequently create these markers.

## Proposal

Add the ability to create a marker on the destination chain using a source chain transaction. Similar to the regular marker creation message, the source message should be able to define if the marker type and permissions

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Some initial comments on markers that get created on the destination chain:

- Mint/Burn permissions must be disabled for any `ibc/` denom
- Supply must not be 'fixed' on an `ibc` denom because the ibc module will be minting/burning amounts when transferred
- Permissions can be copied from the source to the destination with the exception of the mint/burn grants.  Alternatively these could be copied to show correct source values but they would still need to be disabled at point of use.
- Destination `ibc` markers should not be editable since they are a reflection of the source.  It may be easiest to enforce this by removal of grants.  The `deposit`/`withdraw`/`transfer` grants are likely still applicable on the destination chain however any smart contracts used for management will have a different address on the destination chain (if they exist at all).
- When the source marker is edited (mostly grants) they should be replicated to the destination chain(s).  There may be limitations on these features which should be called out in the documentation.

**Comment by iramiller** [comment]
See #1127

**Comment by nullpointer0x00** [comment]
Implemented in #1127

**Comment by nullpointer0x00** [comment]
Overview of implementation.

- Markers sent from source chain will have a name of type `ibc/` on destination chain.  The record will have a `DenomMetaData` associated with it where `Name` and `Display` will be "chain-id/chain-denom" (i.e pio-testnet-1/nhash)  and `Description` is "chain-denom is from chain-id" (i.e. nhash is from pio-testnet-1). 
- Markers are created without Mint/Burn permissions.
- Markers are only created with transfer authority grants.  Excluding the other grants ensures the marker immutable from the destination chain.
- Transfer authority permissions are a reflection of the source chains transfer permissions.  If the source chain's transfer permissions are updated.  The next transfer of the marker from source to dest chain will update those permissions.
- `allow_forced_transfer` flag is reflected on the destination chain for restricted markers.  If the source chain's `allow_forced_transfer` flag is changed.  The next transfer of the marker from source to dest chain will update that property.

@jtalis PR #1678  implemented all these changes and is now merged to main.
