### ISSUE TITLE
Create a smart contract to convert between two different currencies

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provenance#1130]
## Summary

Create a smart contract that can easily be deployed and allow users to convert from one currency to another.

## Problem Definition

We do not have a way to easily convert from nhash to other currencies.

## Proposal

Create a smart contract that acts as an exchange between two currencies
- The initialization should take two currencies and their exchange rate
- Implement a method to do the actual exchange.
- Implement a method to update the exchange rate.
- Implement a method to change the contract owner.
- Ensure the correct currencies are used.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
@dcshock 👀

**Comment by arnabmitra** [comment]
i think the consensus is on the `their exchange rate` being a whole number on both sides, e.g 1m `nhash`:10vspn or something similar.

**Comment by iramiller** [comment]
A couple of updates ... exchange rate is 1:1 (no need to get complicated here)... and the fee/bond denom marker should be used to hold the deposited funds in escrow so the balance of the deposited tokens can be compared against the total supply of the minted token (they should match 1:1).  The contract would have mint/burn/deposit/withdraw authority granted on the marker so that it can use it for book keeping.

**Comment by Taztingo** [comment]
Work for this was done on a separate repo...

https://github.com/provenance-io/ibc

**Comment by arnabmitra** [comment]
@Taztingo can we close this?
