### ISSUE TITLE
Move upgrade schedules into a better location (pkg/*)

### ISSUE THREAD

**Issue by mtps** [provenance-io/provenance#139]
## Summary

Move upgrade schedules into a better code location (pkg/* maybe?) and provide a means to load either testnet or mainnet upgrade plan lists.

## Problem Definition

Why: Testnet and mainnet will be running different upgrade processes yet using the same binary. If the two are to reside in the same repo, a separation will be needed as to which list of handlers to load.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Ideally any upgrade we want to run on the mainnet will have been run on testnet first ... the only disconnect I see is that the testnet will likely run many more upgrades than the mainnet as inevitably some of the test versions will not be suitable for production.

A somewhat related piece to this is the `/internal/legacy/migration.go` section that is used to transform an export from one major release to another for hard forks.  Whatever is chosen for the `pkg` pieces should mesh well with the migration components.

**Comment by SpicyLemon** [comment]
I think we're good on how we currently manage upgrades.

We want mainnet and testnet to both use the exact same binary. In order to have only mainnet or only testnet upgrades available, about the only thing we could do is try to work off the absence or presence of the `--testnet` flag. But all the upgrade definition happens before we can correctly check the CLI args and env vars.

I also don't see any harm in having all the upgrades defined even if one or more is never used on the chain.

We purposefully name the upgrades differently (e.g. `umber` vs `umber-rc1`) to distinguish them. Because mainnet and testnet have some slight crucial differences, it's been rare that we could use the same upgrade for both. But we'd still have both, just with the same code. I.e. I don't foresee us doing a non-rc upgrade on testnet, or an rc upgrade on mainnet. They usually need to run through similar steps, but with slightly different values. Also, sometimes one will have an extra step or two because that step isn't needed/wanted on the other chain.
