### ISSUE TITLE
Add upgrade handler migration to enable send for restricted markers

### ISSUE THREAD

**Issue by nullpointer0x00** [provenance-io/provenance#1427]
## Summary

Currently, all restricted markers have been set to SendEnabled false.  With the implementation of https://github.com/provenance-io/provenance/issues/1256 we can delete all items from the table.  This will allow the send restrictions to be applied with the new handler.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
For this migration ... are the "send disabled" records within the bank module simply deleted? Or is there still a record for each token created ... this will have some impact on the management of that configuration within the marker module....

**Comment by nullpointer0x00** [comment]
As of right now, we are setting the send enabled to true(coin) or false(restricted) within from the marker module.  With #1256 I set true for both with our current `ensureSendEnabledStatus` method.  However, we could probably just delete them all and not have our marker module set them.  The cosmos sdk has a parameter that indicates what it should default to if the coin is not found.  On both testnet and mainnet it is set to true.  Therefore, if they all deleted from the table on upgrade IsSendEnabled will be true for the coin.  

It would be nice to delete the `ensureSendEnabledStatus` method from the marker module and have the upgrade remove all entries. @SpicyLemon Thoughts?

**Comment by nullpointer0x00** [comment]
I agree.  It is now removed and I updated the description of the ticket.

**Comment by SpicyLemon** [comment]
Just catching up on this.

I agree with removing `ensureSendEnabledStatus`.

And the only reason to keep all of those `SendEnabled` records around would be in the crazy off-chance that we change the `DefaultSendEnabled` param. I feel like that's pretty far outside the realm of possibilities, though, so it's okay to remove all those records. It'll save a little state, but each is just a key/value pair where the value is a single byte.

But since we need to either update them all to `true` or delete them, might as well just delete them.
