### ISSUE TITLE
Allow marker admin to prevent transfer of restricted coin with deny list on send

### ISSUE THREAD

**Issue by leeduan** [provenance-io/provenance#1518]
## Summary

Allow a marker admin to sanction or add specific addresses to a deny list to prevent that address from transferring that coin to another address.

## Problem Definition

With the introduction of `RequiredAttributes` in the marker module for restricted coins allowing anyone to use the bank module send functionality to any to address with those respective attributes, we can't prevent a from address that the marker admin(s) wants to sanction from transferring that coin to another address with those attributes.

Some example use cases:
* a fiat or stablecoin provider may want to prevent a blockchain address from being able to transfer coin that was minted in relation to an ACH deposit that was later claimed fraudulent.
* a court order notifies a TA to reissue a security token to a new address because old coin is held in an account that is no longer accessible due to lost keys

## Proposal

Allow some kind of marker-specific sanction or deny list so that we prevent bank send on restricted marker with required attributes on from addresses.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nullpointer0x00** [comment]
Yes, I was wondering about this case as well.  For example, if an address is added to the deny list.  We will probably have to look at the account and see if they have any of the restricted markers and do something house keeping if they do.  If they don't, we can just add the address.  We could do this issue without that to begin with.  Just have the ability to add the deny list on marker creation.  That way the denied addresses would not have any markers yet.  Then do all the logic of denying a send.

The next issue would be to make an Update deny list tx.  That could would do all that work.  Since, the address added could have those markers.

**Comment by iramiller** [comment]
After some discussion with Figure about market place restrictions for bilateral settlement we should consider a generic restriction module function for this implementation.  

In the examples discussed in that meeting it is desired that the tokens being exchanged be escrowed in the user’s wallet with a hold placed on committed tokens. This is preferable to a situation with tokens moved into a contract for escrow. 

Along this same line the ability to stop transfer of tokens out of a wallet neatly solves the vesting account setup where there are multiple vesting claims. With a proper hold function that implemented lockups as a service for other modules the marker module could issue a hold, vesting systems could do the same… even a future exchange module could issue and cancel holds for in place escrow of funds.

**Comment by SpicyLemon** [comment]
Did some digging on "Spendable Balance" and locked coins. Currently, the only way to utilize the bank module's concept of "locked coins" is through vesting accounts. We could implement our own custom vesting account type to handle the management of locked funds, but that comes with extra headaches since an account can only be one type. E.g. an account can't be two different types of vesting account.

It'd probably be better to have the marker module manage the state of escrowed funds. The funds would remain in the original account and the marker module would record that they're in escrow. The marker's `SendRestriction` function would be updated to ensure that escrowed funds aren't moved.

One down-side to that is the `SpendableBalance` query would still report that the escrowed funds are spendable. If that's a problem, we could add an injectable `GetLockedCoins` function to the bank module so that the marker module can tell the bank module that some funds are locked.

**Comment by leeduan** [comment]
@iramiller should I open anther ticket for `escrowed in the user’s wallet with a hold placed on committed tokens` feature? did a quick scan of issues but didn't see anything there and assume the deny list feature here will be built separate from a more extensive hold feature?

**Comment by iramiller** [comment]
Sure @leeduan, you could open another issue to formally start tracking that. I have some detail I can add from my exchange module notes but it would be easy to ship separately since it seems you might want this feature sooner than later.

**Comment by leeduan** [comment]
> 

https://github.com/provenance-io/provenance/issues/1607
