### ISSUE TITLE
Provenance Auto Completion

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provenance#1687]
## Summary

It would be very helpful to have auto completion in Provenance. The cobra module provides a way to generate static and dynamic auto completion

## Problem Definition

One barrier that the Provenance Blockchain faces is ease of use. It can be very hard for new users to remember what the commands are, and it can be frustrating to learn the valid types of args and flags. This problem not only affects new users, but also the development and devops teams. All these users are forced to write out entire commands and query the chain for valid arguments.

## Proposal

Introduce a command to the cli to generate the auto completion scripts. Cobra supports auto completion generation for Bash, ZSH, FISH, and PowerShell. We should at least support Bash and ZSH as they are the most popular. It is probably best to start with static auto completion and deal with dynamic creation at a later time since that involves handling asynchronous results.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Not a bad idea to expand the use of the other features Cobra/Viper support.  I would recommend including Fish as well since it is nearly as popular as ZSH (more so before Apple forced the switch to ZSH in the past couple of years).

A point to consider though is that the Cosmos SDK has restructured how command line integration is done in the SDK to greatly reduce the amount of code required.  We would probably be smart to ensure any CLI updates we make are compliant with where the SDK is going.
