### ISSUE TITLE
Investigate new params with SDK v0.50.x update.

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/provenance#2008]
## Summary

The v0.50.0 SDK update has introduced new parameters that need to be reviewed. An analysis is required to evaluate their impact on our chain.

## Problem Definition

These need to be updated in order to ensure our chain behaves properly.

## Proposal

Investigate the following modules and their parameters:

**gov**
- proposal_cancel_ratio
- proposal_cancel_dest
- expedited_voting_period
- expedited_threshold
- expedited_min_deposit
- burn_vote_quorum
- burn_proposal_deposit_prevote
- burn_vote_veto
- min_deposit_ratio
- constitution

**consensus**
- abci
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
Here's some more info on the new params:
New gov params:
* Min deposit stuff:
  * **min initial deposit ratio**: The proportion of the minimum deposit that is required when submitting a proposal.
    Default is `0`.
  * **min deposit ratio**: The percentage of total required deposit required when making a deposit on a proposal. This is also applied when initially submitting a proposal.
    Default is `0.1`.
* Proposal cancelling:
  * **proposal cancel ratio**: The proprtion of the deposit that is NOT returned when a proposal is cancelled.
    Default is `0.5`.
  * **proposal cancel dest**: The address which will receive the funds kept when a proposal is cancelled. If empty, that amount is burned.
    Default is `""`.
* Expedited proposals:
  * **expedited voting period**: Duration of the voting period of an expedited proposal.
    Default is `1 day`.
  * **expedited threshold**: Minimum proportion of yes votes needed for an expedited proposal to pass.
    Default is `0.667`.
  * **expedited min deposit**: Minimum deposit needed on an expedited proposal for it to enter voting period.
    Default is `50000000stake`.
* Deposit burning:
  * **burn vote quorum**: Whether to burn deposits if a proposal does not meet quorum.
    Default `false`.
  * **burn proposal deposit prevote**: Whether to burn deposits if a proposal does not enter voting period.
    Default `false`.
  * **burn vote veto**: Whether to burn deposits if the propoal reaches quorum with a vote result of veto.
    Default `true`.

There's also a new abci param in the tendermint stuff:
* **vote extensions enable height**:
  ```
    // vote_extensions_enable_height configures the first height during which
    // vote extensions will be enabled. During this specified height, and for all
    // subsequent heights, precommit messages that do not contain valid extension data
    // will be considered invalid. Prior to this height, vote extensions will not
    // be used or accepted by validators on the network.
    //
    // Once enabled, vote extensions will be created by the application in ExtendVote,
    // passed to the application for validation in VerifyVoteExtension and given
    // to the application to use when proposing a block during PrepareProposal.
  ```

These are the only new params I found when I went searching.

**Comment by SpicyLemon** [comment]
With the min deposit, for testnet, we probably want it to be '0' (instead of the default '0.1') so that people can submit their proposals without needing to put up any deposit, which is our current way of doing it. For mainnet, I'm not sure what we want to do here.

For proposal cancelling, I feel like we just want zeros (i.e. don't burn anything for cancelling a proposal). But maybe we do? We'll have to consider how burning those deposit funds will affect things.

For expedited proposals, the defaults seem okay to me (with a 5x deposit of 50,000 hash). If anything, we might want to shorten the voting period to maybe 8 hours.

For deposit burning, similar to proposal cancelling, we'll need to consider what effect burning those coins will have. I feel like we shouldn't burn anything though, at least to start. If someone's abusing things, we can reconsider.

I don't know enough about the vote extensions enable height param to make a suggestion. We'll need to figure out what it means for validators. My initial thought here is to use a value that makes it not enabled and later, if we're ready to enable it, submit a gov proposal to update that param. I'm not actually sure if that's possible though. Basically, we need more info here.

**Comment by SpicyLemon** [comment]
After discussion with Ira, I think this is what we settled on. I'll make a PR from this.

For mainnet, we'll want a 1000 hash initial deposit, but don't care about subsequent ones.
For testnet, we don't really want to require an initial deposit because we've got a pretty good flow where we (or others) submit a proposal, then one of us supplies the deposit and the votes. And we'd like to not mess that up too much. But we don't want the min-deposit to be a surprise when doing stuff on mainnet. So we figured we'd set the initial deposit for testnet at 1 hash.

For proposal cancelling, we didn't really iron out a specific number, just that we probably want it. So I'll start it at 50% (the default) and we can adjust from there. We're going to leave the destination empty instead of putting the hash marker's address in there. Having the hash marker's address in there would essentially bypass the burn+mint process that would happen, but we're not certain send restrictions would allow a direct send. So, to be safe, we'll just leave it blank.

For expedited gov props, we'll stick with the 1-day and 2/3 vote, and we'll have the deposit match the normal deposit.

For deposit burning, we'll leave the quorum one at `false`, but enable the other two: prevote and veto. We want it with veto to serve as a penalty for submitting egregious proposals. We want deposits burned if the proposal never gets its full deposit to dissuade spamming of gov props. The required initial deposit for submitting a proposal means the submitter had to put up some funds which will then get burned if the rest isn't added over the next couple days. People will still be able to cancel a proposal to only lose 1/2 the deposit, but they'll still lose something.

For the `vote_extensions_enable_height` field, we'll leave that one untouched, and consider it later when we know more about it and how it affects our chain.

**Comment by SpicyLemon** [comment]
Here's what we went with for the new params:
```
	params := govv1.Params{
		MinInitialDepositRatio:     "0.02", // = 1,000 hash
		MinDepositRatio:            "0",
		ProposalCancelRatio:        "0.5",
		ProposalCancelDest:         "",
		ExpeditedVotingPeriod:      24 hours,
		ExpeditedThreshold:         "0.667",
		ExpeditedMinDeposit:        nil, // Will end up being the current MinDeposit value.
		BurnVoteQuorum:             false,
		BurnProposalDepositPrevote: true,
		BurnVoteVeto:               true,
	}
```

For testnet, all of the above are the same except these:
```
		MinInitialDepositRatio:     "0.00002", // = 1 hash
		ProposalCancelRatio:        "0",
		ExpeditedVotingPeriod:      5 minutes,
		BurnProposalDepositPrevote: false,
```
