### ISSUE TITLE
Refine metadata signer parameter in write requests to use party structure

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#219]
## Summary

Currently the signers and parties are provided separately for WriteRecord endpoints in the metadata module.  The signers list should be of type Party instead of type string.

## Problem Definition

The list of signers and list of parties are redundant and can be combined.  This also streamlines the processing of the request and removes a chance for ambiguous behavior.

## Proposal

Change the type of `signers` from `string` to `Party` and remove the `parties` option within `MsgWriteRecordRequest`.  Review other endpoints that may use validation against party_type lists from contract or record specifications for a similar optimization requirement.  This is a client API breaking change.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dwedul-figure** [comment]
While doing research on this, I think I found something that prevents us from removing the `signers`: changing ownership. For example, if we're removing an owner from a scope, that ex-owner must sign. But that ex-owner can't be in the owners list because we don't want them to be an owner anymore. Even with the `DeleteScopeOwner` endpoint, we still need signers because all current owners need to sign, but we won't be deleting all of them.

That being said, here's some research notes:
* All of the `Msg{endpoint}Request` messages have a `repeated string signers` field except `P8eMemorializeContract`, and the `(Bind|Delete|Modify)OSLocator` endpoints.
* `Scope` has `repeated Party owners`.
* `Session` has `repeated Party parties`.
* `Record` doesn't have any party info.
* `ScopeSpecification` has `repeated string owner_addresses`.
* `ContractSpecification` has `repeated string owner_addresses`.
* `RecordSpecification` doesn't have any party info.
* The Object Store Locator TX messages don't have such fields.

**Comment by iramiller** [comment]
The points above about removing signers are good ones ... the intent here was to use the party structure as the one for signers because it combines the required role attribution with the address... some of the endpoints will still need to have two separate lists (such as the change ownership functions).

There could be some cleanup done to unify the api naming conventions but I am extremely hesitant to make any sort of api update/refactor at this point in the system lifecycle... any perceived "code cleanliness" aspects are simply not worth breaking api compatibility on their own imo.

I would be good with closing this issue as :wont-fix: in light of all of these factors.
