### ISSUE TITLE
Marker denom delimiters

### ISSUE THREAD

**Issue by Gabrinthei** [provenance-io/provenance#244]
## Summary

Related to #84 
Relax the validation expression to allow special characters as delimiters of a denom. 

## Problem Definition

Delimiters for denom would allow clearer, human-readable names. This will provide transparency of markers and the various agreements they can represent.

## Proposal

Allow the current denom validation regex to accept `.`(or your preferred set of delimiters) between characters. Would suggest avoiding any at the beginning or end of the string

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dwedul-figure** [comment]
Note: The cosmos `ValidateDenom` regex is `[a-zA-Z][a-zA-Z0-9/]{2,127}`. In some cases, I know the denom string must pass that regex, but I don't know if it must pass for all uses. I'm guessing that's primarily for a single denom rather than a delimited list of them though.

The default `UnrestrictedDenomRegex` is `[a-zA-Z][a-zA-Z0-9/]{2,64}`, but I'm pretty sure we're using something like `[a-zA-Z][a-zA-Z0-9]{4,64}` now. 

1. Both the cosmos regex and our own are tested using `MatchString`. As such, the cosmos regex will pass with a string like `"___abc"` because the regex applies to any part of the string. I think we want to wrap our `UnrestrictedDenomRegex` in `^` and `$` ensuring that the whole string matches, though.
1. We added a bunch of stuff for SI prefixes, and the SI Prefix symbol for "micro" is `µ`. So that character should be added to the first character group for sure, and possibly the second. Since it technically needs to be at the start of a denom, the regex could be expanded to reflect this, but since its enforced elsewhere, it's probably overkill.

**Comment by iramiller** [comment]
> Both the cosmos regex and our own are tested using MatchString.
This is incorrect because when the coin validation denom regex is instantiated in the SDK it always surrounds the expression with the start/end anchors.  Issue #260 updates our marker module unrestricted denom to use the same approach and adds further validation to protect these conventions.

Based on the base SDK support for the `/` char ... and the fact that is was added to the mainnet configuration we should consider using this delimiter if possible.  Would this work for you @Gabrinthei ?

**Comment by Gabrinthei** [comment]
Yes, that will be perfect, @iramiller. Thank you!
