### ISSUE TITLE
Add sort order to Marker.getHolders request/response

### ISSUE THREAD

**Issue by ghost** [provenance-io/provenance#286]
## Summary

Add sort order to Marker.getHolders request/response

## Problem Definition

Right now the paginated list of holders that is returned is not in any real order. It would be nice to add a default sort to the query, or allow the input of a sort order.

## Proposal

Either:
1) add a default sort order to the query, ideally on balance descending, or
2) allow for the user to pass in a sort order on a field and sort direction. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Note: by default all iterators are sorted based on the key ... in this case that would be the address of the account holder.  As that value is based on a hash it should appear random... but will be consistent.  Creating a sort based on balance or similar would require a new account index.  This could be problematic for the marker module since the bank module is doing the majority of the work here.

**Comment by iramiller** [comment]
We can't support this capability within the current blockchain state database right now.
