### ISSUE TITLE
V1.4.0 testnet node failed to send Tendermint metrics to Datadog

### ISSUE THREAD

**Issue by xysblob** [provenance-io/provenance#385]
I've a testnet node that is currently syncing at `v1.4.1` and installed the datadog agent to listen to port 26660 to collect the metrics, yet the datadog was only able to capture metric like `go_threads` but not `tendermint_consensus_height`. I'm using the same `config`.toml as mainnet and datadog has no problem capture the mainnet's metrics.

From what I've read, the attribute gauge that breaks prometheus metrics have been fixed since `v1.3.1`
`https://github.com/provenance-io/provenance/issues/315`

Would appreciate if anyone has any insight of what might went wrong.

**Comment by iramiller** [comment]
Quick take: Do you have the api endpoint enabled? I remember something about an interaction with that endpoint and the metrics... you might try enabling the api endpoint if it isn't and see if that gives you the additional Prometheus info you are looking for. Otherwise I can look into it further tomorrow.

**Comment by xysblob** [comment]
@iramiller Yes I believe so. I've assigned that as a variable and set the value as 'true'  in the host config to override the default value.

`app.toml`
[api]

Enable defines if the API server should be enabled.
enable = {{ api_enabled | default('false') }}

Swagger defines if swagger documentation should automatically be registered.
swagger = false

Address defines the API server to listen on.
address = "tcp://0.0.0.0:1317"

MaxOpenConnections defines the number of maximum open connections.
max-open-connections = 1000

RPCReadTimeout defines the Tendermint RPC read timeout (in seconds).
rpc-read-timeout = 10

RPCWriteTimeout defines the Tendermint RPC write timeout (in seconds).
rpc-write-timeout = 0

RPCMaxBodyBytes defines the Tendermint maximum response body (in bytes).
rpc-max-body-bytes = 1000000

EnableUnsafeCORS defines if CORS should be enabled (unsafe - use it at your own risk).
enabled-unsafe-cors = false

`config.toml`
[instrumentation]

When true, Prometheus metrics are served under /metrics on
PrometheusListenAddr.
Check out the documentation for the list of available metrics.
prometheus = "{{ metrics_enabled | default('true') }}"

Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

Maximum number of simultaneous connections.
If you want to accept a larger number than the default, make sure
you increase your OS limits.
0 - unlimited.
max_open_connections = 3

Instrumentation namespace
namespace = "tendermint"

**Comment by iramiller** [comment]
It seems like you have it configured correctly based on your comment. It is possible that your metrics are a bit different because your node is still replicating/syncing... the metrics themselves are published from the code that handles blocks and other processes using defer statements, if those code blocks are not yet running then the metrics will be missing.

**Comment by xysblob** [comment]
@iramiller Thanks will keep you posted once the node is fully synced.

**Comment by xysblob** [comment]
@iramiller The nodes are fully synced and the metrics finally showed up in Datadog. I am going to close this issue now:)
