### ISSUE TITLE
Fix example addresses to use provenance specific HRPs

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#453]
## Summary of Bug

Command line commands were found that use `cosmos1` example addresses instead of an appropriate Provenance HRP.

https://github.com/provenance-io/provenance/blob/a2f1ff60a60b492b4c7a36d16dfe4330c496f8d3/x/metadata/client/cli/query.go#478

https://github.com/provenance-io/provenance/blob/a2f1ff60a60b492b4c7a36d16dfe4330c496f8d3/x/metadata/client/cli/query.go#503

https://github.com/provenance-io/provenance/blob/a2f1ff60a60b492b4c7a36d16dfe4330c496f8d3/x/metadata/client/cli/query.go#533

https://github.com/provenance-io/provenance/blob/05bdc5a10a27929498918895e3901be78e8563f3/x/metadata/client/cli/tx.go#555

https://github.com/provenance-io/provenance/blob/05bdc5a10a27929498918895e3901be78e8563f3/x/metadata/client/cli/tx.go#561

## Version

1.6.0+

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dwedul-figure** [comment]
I did some grepping (ignoring the unit test files). Unless the address string is being made crazily, there shouldn't be any more instances of that hrp.

```
$ grep -Irs --exclude '*_test.go' '"cosmos' *
```
returns a few results from `cmd/provenanced/cmd/config.go` since "cosmos" is a parameter that can be used there, and then several results from proto imports.

```
$ grep -Irs --exclude '*_test.go' cosmos1 *
```
Doesn't return any results.
