### ISSUE TITLE
Update provenance to wasmd with support for v0.45.0

### ISSUE THREAD

**Issue by channa-figure** [provenance-io/provenance#479]
## Summary

The CosmWasm team is releasing a version of wasmd with support for v0.45.0. https://github.com/CosmWasm/wasmd/issues/501 We need to move away from our fork of wasmd and use their version.  

## Problem Definition

We have been managing our own fork of the wasmd module, because it didn't support the version of cosmos-sdk provenance required.  They have a new release that has the cosmos-sdk v0.45.0 support we need.

## Proposal

- [ ] Update the go.mod to use the new version
- [ ] Update the msg handlers to support our new msg fees handler

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
ibc-2.0 requires these address changes now... and given cosmos hub/osmosis/others are on ibc-2.0 that is where we will want to end up as well... so instead of targeting 1.2 we should target 2.0 and update our fork as needed to bring our setup into alignment.  Unfortunately I do not believe the cosmwasm team will have their 1.0.0 release updated on the schedule we need for 1.8.0
