### ISSUE TITLE
Create Scope and record name authz authorization

### ISSUE THREAD

**Issue by dkneisly-figure** [provenance-io/provenance#788]
## Summary

Somewhat related to #568, it would be great to limit grants using the Authz module to individual records in the metadata module.

## Problem Definition

Say you have a set of scopes owned by one party, each containing the same set of records (same names, not data). An owner doesn't currently have the ability to allow a third-party to unilaterally update a single record within a subset of scopes. Instead, they can grant permission at the message level (MsgWriteSessionRequest, MsgWriteRecordRequest, etc.) and would effectively be granting that permission on all scopes that they own. This allows the third-party to update any record in the scope.

While adding a layer of complexity, this feature would allow fine-grained control over who can write to particular records without requiring multi-party signatures when the business use case doesn't call for it.

## Proposal

It would be great if an owner could grant permission to update a single record on all scopes, or a single record on a specific scope.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dwedul-figure** [comment]
There's two aspects to the desired restrictions here.
1. The record being updated is part of a set of scopes that the grantee is allowed to update.
2. The record being updated has a specific name.

We'll want to create a new authorization message type for this. We'll want to discuss its contents and implementation.

Authz grants are unique to a granter, a grantee, and a message type url. If we want to support the `authz` `exec` endpoint, the message type would need to be the `WriteRecord` msg url. If the grant needs to also cover creating sessions in a scope, there isn't a way to do both with a single grant. If we don't care about the `authz` `exec` endpoint, then we're much freer. I suspect that's the case since we implemented things in the metadata module in such a way that the grants can be used when invoking the metadata endpoints directly. Basically, we can create a new msg type url for these new authorizations that the metadata module can apply to whatever endpoints we want.

At the very least, we'll want it to contain the record name. I'd suggest actually having a list of names.

Dictating which scopes the grant is for is where we've got some options:
1. Have the grant contain a list of scope ids. This is simple and straight forward. The downside here is that the list of scopes might end up being very large, which becomes more and more expensive to read and write.
2. Use the attribute module to flag each scope that the grant should apply to. The new authorization would contain the attribute name and attribute value to look for on any give scope. This would require some extra documentation in order for it to be usable. Additionally, it'd require an extra TX for each scope.
3. Maybe do something with the data access field on a scope. The major downside here is that the data access field would now have multiple purposes. However, those purposes might align enough for it to make sense.
4. Add a new field to scopes for identifying the authz grants that are applicable. I don't really like this option, but feel bad about leaving it out. Adding such a field to the scope message breaks the separation of duties. Basically, the new authorization field would contain a field for an identifier. Then in the new field in the scope would be a list of identifiers applicable to that scope. It's basically the same type of setup as using the attribute module.
5. It's very possible that there are other options that I haven't thought of.

Personally, I'd lean towards using the attribute module.

**Comment by iramiller** [comment]
I don't think the grant functions should pollute the metadata object state unless there is no other way. Grants have unique aspects related to expiration and auditing and tagging the existing permission system within metadata with this will not scale to the crazy 1000 users on an object that will ultimately be expected. Better to manage grants as grants and have the permission check gates ask the grant system if there is a configuration in place that's valid for the current user against the current permission check.

**Comment by iramiller** [comment]
We should also consider this in the context of the upcoming ERC721 support that's needed (x/nft in sdk 0.46)

**Comment by dwedul-figure** [comment]
> I don't think the grant functions should pollute the metadata object state unless there is no other way. Grants have unique aspects related to expiration and auditing and tagging the existing permission system within metadata with this will not scale to the crazy 1000 users on an object that will ultimately be expected. Better to manage grants as grants and have the permission check gates ask the grant system if there is a configuration in place that's valid for the current user against the current permission check.

It sounds like we're on the same page then, and option 2 would be best: a combination of a custom authz authorization and the attribute module. The gist of it is that an authz grant would be issued for a grantee for scopes that have a specific attribute (name and value), and only allows writing of records with specific names. The granter would be responsible for creating and applying the attribute to the desired scopes.

The reason that including the scopes in the new authorization is problematic is that grants are stored with a key that's a combination of granter, grantee, and message type url. A granter can't just issue a new grant to a grantee for just the new scope id(s); it'd stomp on the previous grant between the two for that message type url. So it'd have to include ALL scope ids involved on issuance.

If we don't care about the `exec` endpoint that's part of `authz`, we could bastardize the message type url to include the scope id and a grant could be issued for each scope. If there's more than one grantee, this would be more burdensome than just applying an attribute to a scope. So there's a couple reasons not to do it that way.

**Comment by piercetrey-figure** [comment]
What would be the chances of this being complex enough to handle restricting writing a particular set of hashes to a record? I'm thinking specifically of the p8e multiparty scenario, where in the old system (mega-p8e write contract message) would submit a payload with signatures of all participants over the entire data being submitted; while now this will be managed through authz grants allowing the invoking party to submit a set of scope/session/record messages on behalf of all parties involved.

Somewhat related, would there be plans to have metadata module authz grants have an additional expiration option where they could be used, say, once and then be expired (vs. just the time-based expiration that exists today)?

**Comment by dwedul-figure** [comment]
> What would be the chances of this being complex enough to handle restricting writing a particular set of hashes to a record? I'm thinking specifically of the p8e multiparty scenario, where in the old system (mega-p8e write contract message) would submit a payload with signatures of all participants over the entire data being submitted; while now this will be managed through authz grants allowing the invoking party to submit a set of scope/session/record messages on behalf of all parties involved.

That sounds like a different type of authorization that would be needed.

> Somewhat related, would there be plans to have metadata module authz grants have an additional expiration option where they could be used, say, once and then be expired (vs. just the time-based expiration that exists today)?

We could pretty easily make a use-based generic authorization to use instead of the generic authorization. The annoying thing is that the expiration is part of the `grant` instead of the `authorization`, so we can't _replace_ it. Such a grant/authorization would then expire at the expiration date or after so many uses, whichever happens first.

We'd want separate issues for each of those though.

**Comment by SpicyLemon** [comment]
Closing this in favor of #1439
