### ISSUE TITLE
Pin release workflow build environment

### ISSUE THREAD

**Issue by iramiller** [provenance-io/provenance#840]
## Summary

Currently release builds are done with `ubuntu-latest` workers, we should pin this to a specific LTS of ubuntu

## Problem Definition

Having the latest available ubuntu used for the build environment makes it difficult to match install dependencies for users that wish to run our binaries directly.

## Proposal

Change the github workflow configuration to build releases on a specific version of ubuntu that has LTS

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Based on the Ubuntu release timeline it looks like 20.04 LTS is probably the right choice here.

**Comment by dwedul-figure** [comment]
Here's a link to the available runners: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

Looks like `ubuntu-latest` is currently the same as `ubuntu-20.04`.
Also available are `ubuntu-22.04` and `ubuntu-18.04`.

Should we pin the mac os version too? I kind of feel like `macos-latest` is okay to use since the mac build (as far as I know) isn't being used for any validation nodes. But options are `macos-10.15`, `macos-11`, and `macos-12`. Currently `macos-latest` = `macos-11`.
