### ISSUE TITLE
ABCI Request Response Streaming

### ISSUE THREAD

**Issue by egaxhaj** [provenance-io/provenance#940]
## Summary

Enable listening of `BeginBlocker` and `EndBlocker` request/response events to external consumers.

## Problem Definition

Currently block data is accessed through [Queries](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/messages-and-queries.md#queries) which proceed either through Tendermint and the ABCI API, or through the gRPC server. In addition to these queries, it would be beneficial to have a means of streaming ABCI  req/res to external system(s) as they occur in real-time.

**Why do we need this feature?**
 - To provide a means of consuming `BeginBlocker` and `EndBlocker` req/res events in real-time.
 
**What problems may be addressed by introducing this feature?**
- Allow consuming applications of blockchain data to move away from using the query API and gRPC server and into real-time processing from an external resource. 

**What benefits does the Provenance Network stand to gain by including this feature?**
- Consumer applications no longer need to query nodes directly through the query API or through the gRPC server. Instead, events can be consumed from and external system (i.e: Kafka) in real-time. This frees up resources on he node to do block processing. 

**Should this feature be implemented in the Cosmos SDK directly?**
- This feature is already being worked in [ADR-038](https://docs.cosmos.network/master/architecture/adr-038-state-listening.html). However, the current implementation leads to an `AppHash` mismatch who's cause it undetermined at this time. The implementation suggested in this feature is a lightweight version of ADR-038 but **without** the state-listening component.

**Are there any disadvantages of including this feature?**
- No known disadvantages.

Subtasks:
- [ ] #951

## Proposal

Based on the above requirements we will introduce a new `StreamingService` interface and change `app.BeginBlocker` and `app.EndBlocker` implementations.

#### Streaming Service interface
In a new file, `internal/streaming/streaming.go`, we will introduce `StreamService` and `StreamServiceInitializer` interfaces that plug into the `app` and stream out ABCI request and responses.

```go
// StreamingService interface used to hook into the ABCI message processing of the BaseApp
type StreamingService interface {
	// StreamBeginBlocker updates the streaming service with the latest BeginBlock messages
	StreamBeginBlocker(ctx sdk.Context, req abci.RequestBeginBlock, res abci.ResponseBeginBlock)
	// StreamEndBlocker updates the steaming service with the latest EndBlock messages
	StreamEndBlocker(ctx sdk.Context, req abci.RequestEndBlock, res abci.ResponseEndBlock)
}

// StreamServiceInitializer interface initializes StreamService
// implementations which are then registered with the App
type StreamServiceInitializer interface {
	// Init configures and initializes the streaming service
	Init(opts serverTypes.AppOptions, marshaller codec.BinaryCodec) StreamService
}
```

#### Streaming Service initialization

In a new file, `app/streaming/streaming.go`, we will maintain a map of `StreamServiceInitializers` that can be registered with the app via `app.toml` configuration properties.

```go
// StreamServiceInitializers contains a map of predefined StreamServiceInitializer implementations
import (
	"github.com/provenance-io/provenance/app/streaming/trace"
	"github.com/provenance-io/provenance/internal/streaming"
)

// StreamServiceInitializers contains a map of predefined StreamServiceInitializer implementations
var StreamServiceInitializers = map[string]streaming.StreamServiceInitializer{
	"trace": trace.StreamServiceInitializer,
}

```
We are using `app/streaming/kafka` as an example service that can be used for streaming.

#### Configuration properties

```toml
# app.toml

...

# Streaming service configuration
[streaming]

# Enable streaming servie
enabled = true

# Trace streeming service configuration
[streaming.trace]

print_data_to_stdout = true

...
```

#### App registration

We will add a new method to the `App` to register `StreamingService`s.

```go
// RegisterStreamingService is used to register a streaming service into the App
func (app *App) RegisterStreamingService(s streaming.StreamService) {
	// App will pass BeginBlocker and EndBlocker requests and responses to the streaming services
	app.streamingService = s
}
```

#### App Updates

We will modify `App.BeginBlocker` and `App.EndBlocker` implementations to push req/res events to the `StreamingService` listeners.

```go
// BeginBlocker application updates every begin block
func (app *App) BeginBlocker(ctx sdk.Context, req abci.RequestBeginBlock) abci.ResponseBeginBlock {
	res := app.mm.BeginBlock(ctx, req)
	if app.streamingService != nil {
		app.streamingService.StreamBeginBlocker(ctx, req, res)
	}
	return res
}
```

```go
// EndBlocker application updates every end block
func (app *App) EndBlocker(ctx sdk.Context, req abci.RequestEndBlock) abci.ResponseEndBlock {
	res := app.mm.EndBlock(ctx, req)
	if app.streamingService != nil {
		app.streamingService.StreamEndBlocker(ctx, req, res)
	}
	return res
}
```

#### App wiring

We will update `app.New()` to register streaming services.

```go
func New(...) *App {
    ...
    
    // register streaming service
    streamingEnabled := cast.ToBool(appOpts.Get(fmt.Sprintf("%s.%s", streaming.TomlKey, streaming.EnabledParam)))
	if streamingEnabled {
		service := cast.ToString(appOpts.Get(fmt.Sprintf("%s.%s", streaming.TomlKey, streaming.ServiceParam)))
		ssi, found := appstreaming.StreamServiceInitializers[service]
		if found {
			app.RegisterStreamingService(ssi.Init(appOpts, app.AppCodec()))
			logger.Info("Starting ABCI external streaming", "service", service)
		} else {
			logger.Error("unsupported ABCI streaming service", "service", service)
		}
	}
    
    return app
)
```
 
## Consequences

These changes will stream data out to external system(s).

### Backwards Compatibility

This is new functionality so there should not be issues with backward compatibility.

### Positive

Streaming data to external system(s) will positively effect the system by reducing the burden placed on the node when querying for data through Tendermint and ABCI API or through the gRPC server. This will improve system performance and allow for more resources to be allocated towards block and `Tx` processing. Node operators can also disable gRPC querying all together. 

### Negative

Changes `App.BeginBlocker` and `App.EndBlocker`.

### Neutral

This change introduces additional complexity to configuring and running a node. When opting to enable this feature, the node will rely on external system(s). If the node fails to communicate with the external system(s), the node will not proceed. This will lead to the node falling behind with the rest of the network.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by egaxhaj** [comment]
Closing this in favor of using gRCP to stream events out. See https://github.com/cosmos/cosmos-sdk/pull/11691#issuecomment-1207493282

**Comment by peterbourgon** [comment]
> Currently block data is accessed through [Queries](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/messages-and-queries.md#queries) which proceed either through Tendermint and the ABCI API, or through the gRPC server. In addition to these queries, it would be beneficial to have a means of streaming ABCI req/res to external system(s) as they occur in real-time.

It is literally impossible to stream information to another process with the same guarantees provided by the query API. It boils down to this: what happens when the other process goes down, or can't keep up with the stream?

If you want reliable delivery of events, then you have to buffer events in the full node, which means consuming memory, which will crash once memory is exhausted. In fact, in the queueing theory sense, there's no difference between a buffer of N events and a buffer of 0 events — if the other side can't keep up, and you want reliable delivery, you have to exhibit backpressure (not possible in Cosmos) or crash.

Should a full node crash if an event receiver isn't keeping up? Depends on your perspective. Is a full node's primary responsibility to the network, or to the clients calling its RPC endpoints? 

As an application you can make the case for either one, I guess. Although if you're a validator, it's got to be the former, if you don't want to get slashed! In fact, Tendermint and the SDK are written with the assumption that it's the former, and that assumption is kind of baked-in at every level. It's possible to write protocols that let you pick the latter, for sure, but Tendermint ain't one of them. At least not as it exists today.

(Don't believe me? I don't fault you for it! But try this as an experiment. Patch a full node to deliver events to another process, and crash the node if an event can't be delivered. Be sure to include a reasonably short timeout on event deliveries, like 1s or less. Run this setup for awhile, then kill the receiver, and make sure the full node goes into a crash loop. Wait one hour, then bring the receiver back online. Does everything pick up again where it left off? I have 100 osmo that it doesn't 😉)

Tendermint nodes have a primary responsibility to the network. So they can't really allow third-party processes to impact liveness/availability of consensus. So if an event receiver isn't keeping up, the only viable option is to drop. And that means event delivery can't really be reliable, it has to be best-effort. And that means events can't be used as equivalent to queries.

**Comment by iramiller** [comment]
I suppose I'm thinking of the many times I have synced nodes that are significantly behind the current head of the chain... these nodes sync millions of blocks to catch up... they are restarted during this process and reliably continue exactly where they left off every time. 

This seems to imply that it is perfectly reasonable and in fact a fundamental design of Tendermint blockchains to allow nodes to proceed at their own rate for validating and committing transactions.

**Comment by peterbourgon** [comment]
@iramiller 

> these nodes sync millions of blocks to catch up... they are restarted during this process and reliably continue exactly where they left off every time

Wow! Your experience certainly doesn't match mine. But if that's true, then more power to you 👍 How long does it take a node to catch up 1M+ blocks? Fast sync, state sync, or normal replication?
